apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: candidate-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: candidate-ns
spec:
  releaseName: candidate-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: https://github.com/devrehuman/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: candidate-dtg
      namespace: candidate-ns
    organization:
      name: candidate
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"rehuman-trustee","dest":"9izfDTkfhNpp7qRV2zv4Fn","role":"0","verkey":"5knUMTPtsy8CHBKaHkFsbMQtoEaFPAdEmP21qXdMZVA5"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"recruiter-steward-1","dest":"CjqdeyNz5MogujR5t5heKa","role":"2","verkey":"7Q5eWF1mZyb1Hkx5Y8PggyCNESMKe5XgSn6NRTWqsrMV"},"metadata":{"from":"9izfDTkfhNpp7qRV2zv4Fn"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"recruiter-steward-2","dest":"7s2KxtViAiAD2kHZKbVh1C","role":"2","verkey":"4jwHhKqxeAUqHkszzguHQLbVGEDLTT7ggHYytJ2ztD9E"},"metadata":{"from":"9izfDTkfhNpp7qRV2zv4Fn"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"candidate-steward-1","dest":"XdkaCFujWwTyaxNQmrtVrV","role":"2","verkey":"HhPcMc7PUnpJkA15upCg19UhkUcncTyLKhEoxXLLNKWV"},"metadata":{"from":"9izfDTkfhNpp7qRV2zv4Fn"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"candidate-steward-2","dest":"Rw2BDTu9ZDVCBjv9smkubW","role":"2","verkey":"Eb8YzkV7pz3mKDZExbXVfh5szH2uaHXh8V9isD8oJix5"},"metadata":{"from":"9izfDTkfhNpp7qRV2zv4Fn"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
