apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: recruiter-recruiter-steward-2-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: recruiter-ns
spec:
  releaseName: recruiter-recruiter-steward-2-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: https://github.com/devrehuman/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: recruiter-recruiter-steward-2-auth-job
      namespace: recruiter-ns
    network:
      name: baf
      kubernetes_url: https://380A1ED428E7A314C2CBF481CC481214.gr7.us-east-1.eks.amazonaws.com
    image:
      name: recruiter
      repository: alpine:3.9.4
    vault:
      address: http://afb935f896b2b4869a4c52a7d3570e37-1293396774.us-east-1.elb.amazonaws.com:8200
      keyPath: recruiter.stewards
      identity: recruiter-steward-2
      admin_auth_path: kubernetes-recruiter-admin-auth
      policy: recruiter-recruiter-steward-2-ro
      policy_content: path \"/recruiter/stewards/recruiter-steward-2/*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-recruiter-recruiter-steward-2-auth
    account:
      admin_service: recruiter-admin-vault-auth
      admin_role: rw
      service: recruiter-recruiter-steward-2-vault-auth
      role: ro
