apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: recruiter-recruiter-endorser-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: recruiter-ns
spec:
  releaseName: recruiter-recruiter-endorser-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: https://github.com/devrehuman/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: recruiter-recruiter-endorser-auth-job
      namespace: recruiter-ns
    network:
      name: baf
      kubernetes_url: https://52E456F30AB87D6DE25422D5EAB6B07A.gr7.us-east-1.eks.amazonaws.com
    image:
      name: recruiter
      repository: alpine:3.9.4
    vault:
      address: http://a60f9ef9306654131bf953d0d7ea362c-51415237.us-east-1.elb.amazonaws.com:8200
      keyPath: recruiter.endorsers
      identity: recruiter-endorser
      admin_auth_path: kubernetes-recruiter-admin-auth
      policy: recruiter-recruiter-endorser-ro
      policy_content: path \"/recruiter/endorsers/recruiter-endorser/*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-recruiter-recruiter-endorser-auth
    account:
      admin_service: recruiter-admin-vault-auth
      admin_role: rw
      service: recruiter-recruiter-endorser-vault-auth
      role: ro
