apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: candidate-candidate-steward-1-node
  annotations:
    fluxcd.io/automated: "false"
  namespace: candidate-ns
spec:
  releaseName: candidate-candidate-steward-1-node
  chart:
    path: platforms/hyperledger-indy/charts/indy-node
    git: https://github.com/devrehuman/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: candidate-candidate-steward-1-node
      namespace: candidate-ns
    network:
      name: baf
    organization:
      name: candidate
    genesis:
      pool: Z2VuZXNpcy9wb29sX3RyYW5zYWN0aW9uc19nZW5lc2lz
      domain: ZG9tYWluL2RvbWFpbl90cmFuc2FjdGlvbnNfZ2VuZXNpcw==
      add_org: False
    image:
      pullSecret: regcred
      initContainer:
        name: candidate-candidate-steward-1-node-init
        repository: alpine:3.9.4
      cli:
        name: candidate-candidate-steward-1-node-ledger-txn
        repository: index.docker.io/hyperledgerlabs/indy-ledger-txn:latest
        pullSecret: regcred  
      indyNode:
        name: candidate-candidate-steward-1-node
        repository: index.docker.io/hyperledgerlabs/indy-node:1.11.0
    node:
      name: candidate-steward-1
      ip: 0.0.0.0
      publicIp: 184.73.23.76
      port: 9731
      ambassadorPort: 9731
    client:
      publicIp: 184.73.23.76
      ip: 0.0.0.0
      port: 9732
      ambassadorPort: 9732
    service:
      type: ClusterIP
      ports:
        nodePort: 9731
        nodeTargetPort: 9731
        clientPort: 9732
        clientTargetPort: 9732
    configmap:
      indyConfig: |-
        NETWORK_NAME = 'baf'
        # Enable stdout logging
        enableStdOutLogging = True
        logRotationBackupCount = 10
        # Directory to store ledger.
        LEDGER_DIR = '/var/lib/indy/data'
        # Directory to store logs.
        LOG_DIR = '/var/log/indy'
        # Directory to store keys.
        KEYS_DIR = '/var/lib/indy/keys'
        # Directory to store genesis transactions files.
        GENESIS_DIR = '/var/lib/indy/genesis'
        # Directory to store backups.
        BACKUP_DIR = '/var/lib/indy/backup'
        # Directory to store plugins.
        PLUGINS_DIR = '/var/lib/indy/plugins'
        # Directory to store node info.
        NODE_INFO_DIR = '/var/lib/indy/data'
    ambassador:
      annotations: |-
        ---
        apiVersion: ambassador/v1
        kind: TCPMapping
        name: candidate-candidate-steward-1-node-node-mapping
        port: 9731
        service: candidate-candidate-steward-1-node.candidate-ns:9731
        ---
        apiVersion: ambassador/v1
        kind: TCPMapping
        name: candidate-candidate-steward-1-node-client-mapping
        port: 9732
        service: candidate-candidate-steward-1-node.candidate-ns:9732
    vault:
      address: http://a60f9ef9306654131bf953d0d7ea362c-51415237.us-east-1.elb.amazonaws.com:8200
      serviceAccountName: candidate-candidate-steward-1-vault-auth
      keyPath: /keys/baf/keys/candidate-steward-1
      authPath: kubernetes-candidate-candidate-steward-1-auth
      nodeId: candidate-steward-1
      role: ro
    storage:
      data:
        storagesize: 3Gi
        storageClassName: candidate-aws-baremetal-storageclass
      keys:
        storagesize: 3Gi
        storageClassName: candidate-aws-baremetal-storageclass
