apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rehuman-baf-ac-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: rehuman-ns
spec:
  releaseName: rehuman-baf-ac-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: https://github.com/devrehuman/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: rehuman-baf-ac-auth-job
      namespace: rehuman-ns
    network:
      name: baf
      kubernetes_url: https://52E456F30AB87D6DE25422D5EAB6B07A.gr7.us-east-1.eks.amazonaws.com
    image:
      name: rehuman
      repository: alpine:3.9.4
    vault:
      address: http://a60f9ef9306654131bf953d0d7ea362c-51415237.us-east-1.elb.amazonaws.com:8200
      keyPath: rehuman.baf-ac
      identity: baf-ac
      admin_auth_path: kubernetes-rehuman-admin-auth
      policy: rehuman-baf-ac-ro
      policy_content: path \"/rehuman/+/+/+/public*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-rehuman-baf-ac-auth
    account:
      admin_service: rehuman-admin-vault-auth
      admin_role: rw
      service: rehuman-baf-ac-vault-auth
      role: ro
