apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: candidate-endorser
  annotations:
    fluxcd.io/automated: "false"
  namespace: candidate-ns
spec:
  releaseName: candidate-endorser-faber
  chart:
    path: examples/identity-app/charts/faber
    git: https://github.com/devrehuman/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      namespace: candidate-ns
      name: candidate-endorser
    organization:
      name: candidate
    image:
      pullSecret: regcred
      init:
        name: certs-init
        repository: alpine:3.9.4
      agent:
        name: candidate-endorser
        repository: index.docker.io/sownak/aries-agents:1.11.0
    service:
      ports: 
        service: 15033
        endpoint: 15034
      
      address: candidate-endorser.indy.rehuman.link
      
      ledger: http://rehuman-webserver.indy.rehuman.link:15010
      genesis: http://rehuman-webserver.indy.rehuman.link:15010/genesis
    vault:
      address: http://ab6b85dc5c22d4a5ca37f071617a15fa-2099287404.us-east-1.elb.amazonaws.com:8200
      serviceAccountName: candidate-candidate-endorser-vault-auth
      authPath: kubernetes-candidate-candidate-endorser-auth
      endorserName: candidate-endorser
      role: ro
    storage:
      size: 128Mi
      className: candidate-aws-baremetal-storageclass
    proxy:
      
      provider: "ambassador"
