apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: candidate-candidate-endorser-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: candidate-ns
spec:
  releaseName: candidate-candidate-endorser-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: https://github.com/devrehuman/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: candidate-candidate-endorser-auth-job
      namespace: candidate-ns
    network:
      name: baf
      kubernetes_url: https://52E456F30AB87D6DE25422D5EAB6B07A.gr7.us-east-1.eks.amazonaws.com
    image:
      name: candidate
      repository: alpine:3.9.4
    vault:
      address: http://a60f9ef9306654131bf953d0d7ea362c-51415237.us-east-1.elb.amazonaws.com:8200
      keyPath: candidate.endorsers
      identity: candidate-endorser
      admin_auth_path: kubernetes-candidate-admin-auth
      policy: candidate-candidate-endorser-ro
      policy_content: path \"/candidate/endorsers/candidate-endorser/*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-candidate-candidate-endorser-auth
    account:
      admin_service: candidate-admin-vault-auth
      admin_role: rw
      service: candidate-candidate-endorser-vault-auth
      role: ro
