apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: candidate-admin-vault-auth-cluster-admin-role-binding
  namespace: candidate-ns
  labels:
    organization: candidate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: candidate-admin-vault-auth
  namespace: candidate-ns
