apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: recruiter-recruiter-endorser-transaction
  annotations:
    fluxcd.io/automated: "false"
  namespace: recruiter-ns
spec:
  releaseName: recruiter-recruiter-endorser-transaction
  chart:
    path: platforms/hyperledger-indy/charts/indy-ledger-txn
    git: https://github.com/devrehuman/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: recruiter-recruiter-endorser-transaction
      namespace: recruiter-ns
    network:
      name: demo
    genesis:
      pool: Z2VuZXNpcy9wb29sX3RyYW5zYWN0aW9uc19nZW5lc2lz
      domain: ZG9tYWluL2RvbWFpbl90cmFuc2FjdGlvbnNfZ2VuZXNpcw==
      add_org: False
    image:
      cli:
        name: recruiter
        repository: index.docker.io/hyperledgerlabs/indy-ledger-txn:latest
        pullSecret: regcred
    vault:
      address: http://ab6b85dc5c22d4a5ca37f071617a15fa-2099287404.us-east-1.elb.amazonaws.com:8200
      role: rw
      serviceAccountName: recruiter-admin-vault-auth
      auth_path: kubernetes-recruiter-admin-auth
    organization:
      name: recruiter
      adminIdentity:
        name: rehuman-trustee
        did: 6XUwvPv4gSdtehqdJ13vE2
        path: rehuman/trustees
      newIdentity:
        name: recruiter-endorser
        role: ENDORSER
        did: CAvsXTeBjUdnpRTvTW1B9V
        verkey: 769Jp25kM8cxRLFhpzfHnsykRChrANKYQ5jXEjESSynV
        path: recruiter/endorsers
    node:
      name: recruiter
