apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: recruiter-recruiter-endorser-transaction
  annotations:
    fluxcd.io/automated: "false"
  namespace: recruiter-ns
spec:
  releaseName: recruiter-recruiter-endorser-transaction
  chart:
    path: platforms/hyperledger-indy/charts/indy-ledger-txn
    git: https://github.com/devrehuman/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: recruiter-recruiter-endorser-transaction
      namespace: recruiter-ns
    network:
      name: baf
    genesis:
      pool: Z2VuZXNpcy9wb29sX3RyYW5zYWN0aW9uc19nZW5lc2lz
      domain: ZG9tYWluL2RvbWFpbl90cmFuc2FjdGlvbnNfZ2VuZXNpcw==
      add_org: False
    image:
      cli:
        name: recruiter
        repository: index.docker.io/hyperledgerlabs/indy-ledger-txn:latest
        pullSecret: regcred
    vault:
      address: http://a60f9ef9306654131bf953d0d7ea362c-51415237.us-east-1.elb.amazonaws.com:8200
      role: rw
      serviceAccountName: recruiter-admin-vault-auth
      auth_path: kubernetes-recruiter-admin-auth
    organization:
      name: recruiter
      adminIdentity:
        name: rehuman-trustee
        did: 9izfDTkfhNpp7qRV2zv4Fn
        path: rehuman/trustees
      newIdentity:
        name: recruiter-endorser
        role: ENDORSER
        did: 5fRyDyP3uiwcV2YJU5Hfi8
        verkey: 3YPqoaPyPMp6VoKWxwvsNSv22Ga83i4fYumr3NVJcWbd
        path: recruiter/endorsers
    node:
      name: recruiter
