apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: candidate-candidate-steward-1-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: candidate-ns
spec:
  releaseName: candidate-candidate-steward-1-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: https://github.com/devrehuman/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: candidate-candidate-steward-1-auth-job
      namespace: candidate-ns
    network:
      name: baf
      kubernetes_url: https://380A1ED428E7A314C2CBF481CC481214.gr7.us-east-1.eks.amazonaws.com
    image:
      name: candidate
      repository: alpine:3.9.4
    vault:
      address: http://afb935f896b2b4869a4c52a7d3570e37-1293396774.us-east-1.elb.amazonaws.com:8200
      keyPath: candidate.stewards
      identity: candidate-steward-1
      admin_auth_path: kubernetes-candidate-admin-auth
      policy: candidate-candidate-steward-1-ro
      policy_content: path \"/candidate/stewards/candidate-steward-1/*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-candidate-candidate-steward-1-auth
    account:
      admin_service: candidate-admin-vault-auth
      admin_role: rw
      service: candidate-candidate-steward-1-vault-auth
      role: ro
