apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: candidate-candidate-endorser-transaction
  annotations:
    fluxcd.io/automated: "false"
  namespace: candidate-ns
spec:
  releaseName: candidate-candidate-endorser-transaction
  chart:
    path: platforms/hyperledger-indy/charts/indy-ledger-txn
    git: https://github.com/devrehuman/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: candidate-candidate-endorser-transaction
      namespace: candidate-ns
    network:
      name: baf
    genesis:
      pool: Z2VuZXNpcy9wb29sX3RyYW5zYWN0aW9uc19nZW5lc2lz
      domain: ZG9tYWluL2RvbWFpbl90cmFuc2FjdGlvbnNfZ2VuZXNpcw==
      add_org: False
    image:
      cli:
        name: candidate
        repository: index.docker.io/hyperledgerlabs/indy-ledger-txn:latest
        pullSecret: regcred
    vault:
      address: http://afb935f896b2b4869a4c52a7d3570e37-1293396774.us-east-1.elb.amazonaws.com:8200
      role: rw
      serviceAccountName: candidate-admin-vault-auth
      auth_path: kubernetes-candidate-admin-auth
    organization:
      name: candidate
      adminIdentity:
        name: rehuman-trustee
        did: GFGb4a6MrozquUUc2fNHD2
        path: rehuman/trustees
      newIdentity:
        name: candidate-endorser
        role: ENDORSER
        did: TqBq64ecjLiD49TZU9D1c1
        verkey: FdB8XK6APBpxmNggtMcXNqr57X7VHFcQe2UxBC2PQFRP
        path: candidate/endorsers
    node:
      name: candidate
