apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: candidate-candidate-steward-2
  annotations:
    fluxcd.io/automated: "false"
  namespace: candidate-ns
spec:
  releaseName: candidate-candidate-steward-2
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: https://github.com/devrehuman/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: candidate-candidate-steward-2
      namespace: candidate-ns
    network:
      name: demo
    image:
      name: candidate
      repository: index.docker.io/hyperledgerlabs/indy-key-mgmt:1.11.0
      pullSecret: regcred
    vault:
      address: http://ab6b85dc5c22d4a5ca37f071617a15fa-2099287404.us-east-1.elb.amazonaws.com:8200
      keyPath: candidate.stewards
      identity: candidate-steward-2
      auth_path: kubernetes-candidate-admin-auth
    account:
      service: candidate-admin-vault-auth
      role: rw
