apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: candidate-candidate-endorser
  annotations:
    fluxcd.io/automated: "false"
  namespace: candidate-ns
spec:
  releaseName: candidate-candidate-endorser
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: https://github.com/devrehuman/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: candidate-candidate-endorser
      namespace: candidate-ns
    network:
      name: baf
    image:
      name: candidate
      repository: index.docker.io/hyperledgerlabs/indy-key-mgmt:1.11.0
      pullSecret: regcred
    vault:
      address: http://a60f9ef9306654131bf953d0d7ea362c-51415237.us-east-1.elb.amazonaws.com:8200
      keyPath: candidate.endorsers
      identity: candidate-endorser
      auth_path: kubernetes-candidate-admin-auth
    account:
      service: candidate-admin-vault-auth
      role: rw
