apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rehuman-webserver
  annotations:
    fluxcd.io/automated: "false"
  namespace: rehuman-ns
spec:
  releaseName: rehuman-webserver
  chart:
    path: examples/identity-app/charts/webserver
    git: https://github.com/devrehuman/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      namespace: rehuman-ns
      name: rehuman-webserver
    organization:
      name: rehuman
    image:
      pullSecret: regcred
      init:
        name: rehuman-webserver-init
        repository: alpine:3.9.4
      server:
        name: rehuman-webserver
        repository: index.docker.io/sownak/von-network-base:1.11.0
    service:
      port: 8000
    vault:
      address: http://a60f9ef9306654131bf953d0d7ea362c-51415237.us-east-1.elb.amazonaws.com:8200
      serviceAccountName: rehuman-rehuman-trustee-vault-auth
      authPath: kubernetes-rehuman-rehuman-trustee-auth
      trusteeName: rehuman-trustee
      role: ro
    storage:
      size: 128Mi
      className: rehuman-aws-baremetal-storageclass
    proxy:
      
      provider: "ambassador"
      external_url: rehuman-webserver.indy.rehuman.com
      port: 15010
