apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: recruiter-recruiter-steward-1-vault-auth-role-binding
  namespace: recruiter-ns
  labels:
    organization: recruiter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: recruiter-recruiter-steward-1-vault-auth
  namespace: recruiter-ns
