apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: candidate-candidate-steward-1
  annotations:
    fluxcd.io/automated: "false"
  namespace: candidate-ns
spec:
  releaseName: candidate-candidate-steward-1
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: https://github.com/devrehuman/blockchain-automation-framework.git
    ref: master
  values:
    metadata:
      name: candidate-candidate-steward-1
      namespace: candidate-ns
    network:
      name: baf
    image:
      name: candidate
      repository: index.docker.io/hyperledgerlabs/indy-key-mgmt:1.11.0
      pullSecret: regcred
    vault:
      address: http://afb935f896b2b4869a4c52a7d3570e37-1293396774.us-east-1.elb.amazonaws.com:8200
      keyPath: candidate.stewards
      identity: candidate-steward-1
      auth_path: kubernetes-candidate-admin-auth
    account:
      service: candidate-admin-vault-auth
      role: rw
